#!/bin/sh
set -eu

CONFIG_FILE="/usr/share/nginx/html/app-config.js"

write_config() {
  cat > "$CONFIG_FILE" <<EOF
window.__APP_CONFIG__ = {
  DATABASE_PROVIDER: "${DATABASE_PROVIDER:-${VITE_DATABASE_PROVIDER:-local}}",
  VITE_DATABASE_PROVIDER: "${VITE_DATABASE_PROVIDER:-${DATABASE_PROVIDER:-local}}",
  SUPABASE_URL: "${SUPABASE_URL:-${VITE_SUPABASE_URL:-}}",
  VITE_SUPABASE_URL: "${VITE_SUPABASE_URL:-${SUPABASE_URL:-}}",
  SUPABASE_PUBLISHABLE_KEY: "${SUPABASE_PUBLISHABLE_KEY:-${VITE_SUPABASE_PUBLISHABLE_KEY:-}}",
  VITE_SUPABASE_PUBLISHABLE_KEY: "${VITE_SUPABASE_PUBLISHABLE_KEY:-${SUPABASE_PUBLISHABLE_KEY:-}}"
};
EOF
}

write_config
